[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "odoo_fastapi_demo"
authors = [{name = "St\u00e9phane Bidoul", email = "stephane.bidoul@acsone.eu"}]
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = ["fastapi", "uvicorn[standard]", "gunicorn", "odoo"]
